name: woo_ah_yeah
description: 우리 아기 예방접종
publish_to: none
version: 0.0.1
isar_version: &isar_version 3.1.0

environment:
  sdk: 3.1.2
  flutter: 3.7.12

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: 6.0.5
  intl: 0.17.0
  webview_flutter: 4.0.2
  flutter_svg: 2.0.7
  fluttertoast: 8.2.2
  shared_preferences: 2.2.1
  sqflite: 2.3.0
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core
  path_provider: 2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: *isar_version
  build_runner: any

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - assets/image/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
